networks:
  goldex-network:
    external: true

services:
  masoud-portfolio:
    build: .
    container_name: masoud_portfolio_app
    restart: always
    networks:
      - goldex-network
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
