networks:
  goldex-network:
    external: true

services:
  masoud-portfolio:
    build: .
    image: reg.goldexsoft.ir/masoud-portfolio:latest
    container_name: masoud-portfolio
    restart: always
    networks:
      - goldex-network
    expose:
      - "80"
    environment:
      - NODE_ENV=production
